#fourth_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
  four_wheel_steering_controller:
    type        : "four_wheel_steering_controller/FourWheelSteeringController"
    front_wheel: ['fl_wheel', 'fr_wheel']
    rear_wheel: ['rl_wheel', 'rr_wheel']
    front_steering: ['fl_steering_wheel', 'fr_steering_wheel']
    rear_steering: ['rl_steering_wheel', 'rr_steering_wheel']
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 25.0 # not tested here

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    # wheel_separation : 0.122
    wheel_separation_h : 0.36
    wheel_separation_w : 0.34317
    wheel_radius : 0.085
    wheel_steering_y_offset : -0.1
    # wheel_steering_x_offset : 0.03

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0
    
    # Base frame_id
    # base_frame_id: base_footprint #default: base_link
    base_frame_id: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.667  # m/s
        min_velocity           : -1.667 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.14  # rad/s
        min_velocity           : -3.14
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0

    /gazebo_ros_control:
      pid_gains:
        fl_steering_wheel:
          p: 300
          i: 0
          d: 10
        fr_steering_wheel:
          p: 300
          i: 0
          d: 10
        rl_steering_wheel:
          p: 300
          i: 0
          d: 10
        rr_steering_wheel:
          p: 300
          i: 0
          d: 10
        fl_wheel: #front_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        fr_wheel: #front_right_wheel
          p: 10.0
          i: 1
          d: 0.0
        rl_wheel: #rear_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        rr_wheel: #rear_right_wheel
          p: 10.0
          i: 1
          d: 0.0
          
        # fl_wheel: #front_left_wheel
        #   p: 10.0
        #   i: 1
        #   d: 0.0
        # fr_wheel: #front_right_wheel
        #   p: 10.0
        #   i: 1
        #   d: 0.0
        # rl_wheel: #rear_left_wheel
        #   p: 10.0
        #   i: 1
        #   d: 0.0
        # rr_wheel: #rear_right_wheel
        #   p: 10.0
        #   i: 1
        #   d: 0.0
